create table if not exists public.swims (
  id bigint generated by default as identity primary key,
  date date not null,
  distance_miles numeric(5, 2) not null check (distance_miles > 0),
  notes text,
  created_at timestamptz not null default now()
);

alter table public.swims enable row level security;

create policy "Anyone can read swims"
  on public.swims
  for select
  to anon
  using (true);

create policy "Anyone can log swims"
  on public.swims
  for insert
  to anon
  with check (true);

grant usage on schema public to anon;
grant select, insert on public.swims to anon;
